version: "3.9"
services:
  distService:
    image: convertmaster:latest
    container_name: convertmaster
    restart: unless-stopped
    environment:
      - PORT=9081
      - TEMPPATH=/var/tmp/
      
    ports:
      - "9081:9081"
    volumes:
      - /var/tmp/convertMaster/logs:/var/tmp/convertMaster/logs
    command: ./dist/app -l /var/tmp/convertMaster/logs/converter.log
    networks:
      - converter-network
networks:
    converter-network:
      external: true