version: "3.9"
services:
  distService:
    image: convertmaster:latest
    container_name: convertmaster
    restart: unless-stopped
    environment:
      - PORT=9081
      - TEMPPATH=/var/tmp/convertMaster
      - MAX_REQUESTS=3
      - APP_DOMAIN=APP_DOMAIN_VALUE
      - POSTGRES_DSN=POSTGRES_DSN_VALUE
      - MONTHLY_OFFLINE_PRICE_ID=MONTHLY_OFFLINE_PRICE_ID_VALUE
      - YEARLY_OFFLINE_PRICE_ID=YEARLY_OFFLINE_PRICE_ID_VALUE
      - MONTHLY_ONLINE_PRICE_ID=MONTHLY_ONLINE_PRICE_ID_VALUE
      - YEARLY_ONLINE_PRICE_ID=YEARLY_ONLINE_PRICE_ID_VALUE
      - DAILY_PRICE_ID=DAILY_PRICE_ID_VALUE
      - STRIPE_KEY=STRIPE_KEY_VALUE
      - STRIPE_ENDPOINT_SECRET=STRIPE_ENDPOINT_SECRET_VALUE
      - AWS_ACCESS_KEY=AWS_ACCESS_KEY_VALUE
      - AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY_VALUE
      - AWS_REGION=AWS_REGION_VALUE
      - AWS_BUCKET=AWS_BUCKET_VALUE
    ports:
      - "9081:9081"
    volumes:
      - /var/tmp/convertMaster:/var/tmp/convertMaster
    command: ./dist/app -l /var/tmp/convertMaster/logs/converter.log
    networks:
      - converter-network
networks:
    converter-network:
      external: true