version: "3.9"
services:
  cmClient:
    image: cmclient:latest
    restart: always
    ports:
      - "9080:80"
    environment:
      - REACT_APP_API_URL=CM_APP_API_URL_VALUE

    volumes:
      - /var/tmp/convertMaster/logs:/var/tmp/convertMaster/logs
    networks:
      - converter-network
networks:
    converter-network:
      external: true
