version: "3.9"
services:
  ecClient:
    image: ecclient:latest
    restart: always
    ports:
      - "9080:80"
    environment:
      - REACT_APP_API_URL=EC_APP_API_URL_VALUE

    volumes:
      - /var/tmp/extconvert/logs:/var/tmp/extconvert/logs
    networks:
      - converter-network
networks:
    converter-network:
      external: true
