name: Build Linux Software

on:
  push:
    branches:
      - "main"
    paths:
      - services/converter-sw/**
      - services/converter/**
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libreoffice \
            tesseract-ocr \
            ghostscript \
            p7zip-full \
            ffmpeg \
            python3-dev \
            build-essential \
            libgtk-3-dev \
            wget \
            unzip

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./services/converter/requirements.txt

      - name: Copy converter code
        run: |
          mkdir -p build_app
          cp -r services/converter build_app/converter
          cp -r services/converter-sw/* build_app/

      - name: Build main app full
        shell: bash
        run: |
          cd build_app
          pyinstaller \
            --noconfirm --clean --console --name app \
            --onefile --log-level DEBUG \
            --add-data "build_full:build" \
            --add-data "/usr/lib/libreoffice:dependencies/libreoffice" \
            --add-data "/usr/share/tesseract-ocr:dependencies/tesseract-ocr" \
            --add-data "/usr/bin/ffmpeg:dependencies" \
            --add-data "/usr/bin/gs:dependencies/ghostscript" \
            --add-data "/usr/bin/7z:dependencies/7zip" \
            --distpath ../proc/full main.py

      - name: Build launcher full
        run: |
          cd build_app
          pyinstaller --onefile --windowed --name extconvert \
            --icon=resources/logo.jpg \
            --add-data "resources/logo.jpg:resources" \
            --add-data "../proc/full/app:." \
            --distpath ../output/linux/full launcher.py

      - name: Build main app basic
        shell: bash
        run: |
          cd build_app
          pyinstaller \
            --noconfirm --clean --console --name app \
            --onefile --log-level DEBUG \
            --add-data "build_basic:build" \
            --add-data "/usr/lib/libreoffice:dependencies/libreoffice" \
            --add-data "/usr/share/tesseract-ocr:dependencies/tesseract-ocr" \
            --add-data "/usr/bin/ffmpeg:dependencies" \
            --add-data "/usr/bin/gs:dependencies/ghostscript" \
            --add-data "/usr/bin/7z:dependencies/7zip" \
            --distpath ../proc/basic main.py

      - name: Build launcher basic
        run: |
          cd build_app
          pyinstaller --onefile --windowed --name extconvert \
            --icon=resources/logo.jpg \
            --add-data "resources/logo.jpg:resources" \
            --add-data "../proc/basic/app:." \
            --distpath ../output/linux/basic launcher.py


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp ./output/linux/basic/extconvert s3://convertmasterfiles/software/linux/basic/extconvert
          aws s3 cp ./output/linux/full/extconvert s3://convertmasterfiles/software/linux/full/extconvert