name: Build macOS Software

on:
  push:
    branches:
      - "main"
    paths:
      - services/converter-sw/**
      - services/converter/**
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'

      - name: Install system dependencies
        run: |
          brew update
          brew install --cask libreoffice
          brew install tesseract ghostscript ffmpeg p7zip gtk+3

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./services/converter/requirements.txt

      - name: Copy converter code
        run: |
          mkdir -p build_app
          cp -r services/converter build_app/converter
          cp -r services/converter-sw/* build_app/

      - name: Build main app binary
        run: |
          cd build_app
          pyinstaller \
            --noconfirm --clean --console --name app \
            --onefile --log-level DEBUG \
            --add-data "build:build" \
            --add-data "/Applications/LibreOffice.app:dependencies/libreoffice" \
            --add-data "/opt/homebrew/bin/tesseract:dependencies/tesseract" \
            --add-data "/opt/homebrew/bin/ffmpeg:dependencies" \
            --add-data "/opt/homebrew/bin/gs:dependencies/ghostscript" \
            --add-data "/opt/homebrew/bin/7z:dependencies/7zip" \
            --distpath ../proc main.py

      - name: Build launcher app binary
        run: |
          cd build_app
          pyinstaller --onefile --windowed --name extconvert \
            --icon=resources/logo.jpg \
            --add-data "resources/logo.jpg:resources" \
            --add-data "../proc/app:." \
            --distpath ../output/macos launcher.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp ./output/macos/extconvert s3://extconvertmasterfiles/software/macos/extconvert